### ISSUE TITLE
Cannot find module 'adal-angular'

### ISSUE THREAD

**Issue by woodm1** [benbaran/adal-angular4-example#5]
Getting the following error on ng serve:

ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/adal4.service.d.ts (3,22): Cannot find module 'adal-angular'.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/http/src/backends/browser_jsonp.d.ts (1,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/core/src/errors.d.ts (9,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/core/src/errors.d.ts (10,43): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/core/src/errors.d.ts (11,42): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/core/src/errors.d.ts (12,43): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/core/src/errors.d.ts (13,35): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/core/src/animation/dsl.d.ts (81,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/core/src/animation/animation_metadata_wrapped.d.ts (12,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/common/http/src/jsonp.d.ts (5,44): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/common/http/src/jsonp.d.ts (6,45): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules/@angular/common/http/src/jsonp.d.ts (7,52): Initializers are not allowed in ambient contexts.

Using latest Angular-CLI version. I've tried the fixes suggested at https://github.com/alenny/angular2-adal/issues/8 but they're for the Angular 2 version, and no luck.

Any ideas?

**Comment by arulrajsuri** [comment]
@woodm1 can you please explain, what you did to resolve this issue, i m also in the same boat
